#!/bin/sh

#  '||''|.    .|'''.|  '||''|.  '|| '||'  '|' '||    ||' 
#   ||   ||   ||..  '   ||   ||  '|. '|.  .'   |||  |||  
#   ||'''|.    ''|||.   ||...|'   ||  ||  |    |'|..'||  
#   ||    || .     '||  ||         ||| |||     | '|' ||  
#  .||...|'  |'....|'  .||.         |   |     .|. | .||. 

# Launch SXHKD with config file
sxhkd -c ~/.config/sxhkd/sxhkdrc &

# BSPWM configuration

# Border Gap & Padding
bspc config border_radius        20
bspc config border_width         2

bspc config window_gap           30

bspc config top_padding          5
bspc config bottom_padding       2
bspc config left_padding         2
bspc config right_padding        2

# Monocle
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config borderless_monocle   true

bspc config split_ratio          0.50

# Window focus with mouse
bspc config click_to_focus        true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

# Monitors
bspc monitor eDP-1 -d 1 2 3 4 5 # Laptop Screen
bspc monitor HDMI-1 -d 6 7 8 9 # Home Screen


# Floating applications
bspc rule -a krunner state=floating border=off # border=off for lock position

# Open applications on specific workspaces
bspc rule -a discord desktop='^4'
bspc rule -a Thunderbird desktop='^5'

# Start element on bspwm starter
$HOME/.config/bspwm/autostart.sh
